spring:
  application:
    name: "Struts 2 - Spring Boot"

  datasource:
    url: jdbc:h2:mem:otdb
    driverClassName: org.h2.Driver
    username: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
